// import './Product.css';
// const ProductDetails = [
//     {
//       product_id: 1,
//       name: 'Zen Wall Home Lamps',
//       price: '15000.00',
//       quantity_available: 10,
//       image_url: 'https://sp-ao.shortpixel.ai/client/to_auto,q_glossy,ret_img,w_433,h_516/https://akkaara.co.in/wp-content/uploads/2019/11/21-1-433x516.jpg',
//     },
//     {
//       product_id: 2,
//       name: 'Sculpted Pendant Lamps',
//       price: '7700.00',
//       quantity_available: 15,
//       image_url: 'https://sp-ao.shortpixel.ai/client/to_auto,q_glossy,ret_img,w_433,h_516/https://akkaara.co.in/wp-content/uploads/2019/01/Pendantlight_mproduct_id_product-433x516.jpg',
//     },
//     {
//         product_id: 3,
//         name: 'Regal Candle Stand',
//         price: '7300.00',
//         quantity_available: 15,
//         image_url: 'https://sp-ao.shortpixel.ai/client/to_auto,q_glossy,ret_img,w_433,h_516/https://akkaara.co.in/wp-content/uploads/2019/01/elephant_product1-433x516.jpg',
//       },
//       {
//         product_id: 4,
//         name: 'Nari Smoked Planter',
//         price: '600.00',
//         quantity_available: 15,
//         image_url: 'https://sp-ao.shortpixel.ai/client/to_auto,q_glossy,ret_img,w_433,h_516/https://akkaara.co.in/wp-content/uploads/2019/01/teapot_mproduct_id_product-433x516.jpg',
//       },
//       {
//         product_id: 5,
//         name: 'Painted Dinner Set',
//         price: '4900.00',
//         quantity_available: 15,
//         image_url: 'https://sp-ao.shortpixel.ai/client/to_auto,q_glossy,ret_img,w_433,h_516/https://akkaara.co.in/wp-content/uploads/2019/11/P8_2-433x516.jpg',
//       },
//       {
//         product_id: 6,
//         name: 'Hand-Carved mirror',
//         price: '16500.00',
//         quantity_available: 15,
//         image_url: 'https://sp-ao.shortpixel.ai/client/to_auto,q_glossy,ret_img,w_433,h_516/https://akkaara.co.in/wp-content/uploads/2019/11/45-433x516.jpg',
//       },
//       {
//         product_id: 7,
//         name: 'Hand-Beaten Tea Set',
//         price: '6500.00',
//         quantity_available: 15,
//         image_url: 'https://sp-ao.shortpixel.ai/client/to_auto,q_glossy,ret_img,w_433,h_516/https://akkaara.co.in/wp-content/uploads/2019/01/teapot_mproduct_id_product-433x516.jpg',
//       },
//       {
//         product_id: 8,
//         name: 'Eternal Tea light',
//         price: '3500.00',
//         quantity_available: 15,
//         image_url: 'https://sp-ao.shortpixel.ai/client/to_auto,q_glossy,ret_img,w_433,h_516/https://akkaara.co.in/wp-content/uploads/2019/11/5-433x516.jpg',
//       },
//       {
//         product_id: 9,
//         name: 'Cinoni Clay Decanter',
//         price: '2300.00',
//         quantity_available: 15,
//         image_url: 'https://sp-ao.shortpixel.ai/client/to_auto,q_glossy,ret_img,w_433,h_516/https://akkaara.co.in/wp-content/uploads/2019/11/P2_2-433x516.jpg',
//       },
//       {
//         product_id: 10,
//         name: 'Brass embossed Planter',
//         price: '5500.00',
//         quantity_available: 15,
//         image_url: 'https://sp-ao.shortpixel.ai/client/to_auto,q_glossy,ret_img,w_433,h_516/https://akkaara.co.in/wp-content/uploads/2019/01/lotus_vase_mproduct_id_product-433x516.jpg',
//       },
//       {
//         product_id: 11,
//         name: 'Bala Planter',
//         price: '450.00',
//         quantity_available: 15,
//         image_url: 'https://sp-ao.shortpixel.ai/client/to_auto,q_glossy,ret_img,w_433,h_516/https://akkaara.co.in/wp-content/uploads/2019/09/S1_3-433x516.jpg',
//       },
//       {
//         product_id: 12,
//         name: 'Badak Clay Decanter',
//         price: '2000.00',
//         quantity_available: 15,
//         image_url: 'https://sp-ao.shortpixel.ai/client/to_auto,q_glossy,ret_img,w_433,h_516/https://akkaara.co.in/wp-content/uploads/2019/11/Painted-Waterbottle-433x516.jpg',
//       },
//       {
//         product_id: 13,
//         name: 'Hand Decorated Glass',
//         price: '350.00',
//         quantity_available: 15,
//         image_url: 'https://sp-ao.shortpixel.ai/client/to_auto,q_glossy,ret_img,w_433,h_516/https://akkaara.co.in/wp-content/uploads/2020/08/P4_3-433x516.jpg',
//       },
//       {
//         product_id: 14,
//         name: 'Painted Dinner Set',
//         price: '4900.00',
//         quantity_available: 15,
//         image_url: 'https://sp-ao.shortpixel.ai/client/to_auto,q_glossy,ret_img,w_433,h_516/https://akkaara.co.in/wp-content/uploads/2019/11/P8_2-433x516.jpg',
//       },
//       {
//         product_id: 15,
//         name: 'Painted Serving Bowl',
//         price: '1800.00',
//         quantity_available: 15,
//         image_url: 'https://sp-ao.shortpixel.ai/client/to_auto,q_glossy,ret_img,w_433,h_516/https://akkaara.co.in/wp-content/uploads/2019/11/P7_6-433x516.jpg',
//       },
//       {
//         product_id: 16,
//         name: 'Jewellery Keeper',
//         price: '1300.00',
//         quantity_available: 15,
//         image_url: 'https://sp-ao.shortpixel.ai/client/to_auto,q_glossy,ret_img,w_433,h_516/https://akkaara.co.in/wp-content/uploads/2019/11/P7_6-433x516.jpg',
//       },
//       {
//         product_id: 17,
//         name: 'Khavda Tea Set',
//         price: '2500.00',
//         quantity_available: 15,
//         image_url: 'https://sp-ao.shortpixel.ai/client/to_auto,q_glossy,ret_img,w_433,h_516/https://akkaara.co.in/wp-content/uploads/2019/11/P3_2-433x516.jpg',
//       },
//       {
//         product_id: 18,
//         name: 'Khavda Water Bottle',
//         price: '1200.00',
//         quantity_available: 15,
//         image_url: 'https://sp-ao.shortpixel.ai/client/to_auto,q_glossy,ret_img,w_433,h_516/https://akkaara.co.in/wp-content/uploads/2019/11/P6_1-433x516.jpg',
//       },
//       {
//         product_id: 19,
//         name: 'Martaban Dispenser',
//         price: '2100.00',
//         quantity_available: 15,
//         image_url: 'https://sp-ao.shortpixel.ai/client/to_auto,q_glossy,ret_img,w_433,h_516/https://akkaara.co.in/wp-content/uploads/2019/11/P4_2-433x516.jpg',
//       },
//       {
//         product_id: 20,
//         name: 'Beetle Leaf Plate Set',
//         price: '5300.00',
//         quantity_available: 15,
//         image_url: 'https://sp-ao.shortpixel.ai/client/to_auto,q_glossy,ret_img,w_433,h_516/https://akkaara.co.in/wp-content/uploads/2019/01/leaf_bowl_mproduct_id_product-433x516.jpg',
//       },
//       {
//         product_id: 21,
//         name: 'Brass Wind Chime',
//         price: '2900.00',
//         quantity_available: 15,
//         image_url: 'https://sp-ao.shortpixel.ai/client/to_auto,q_glossy,ret_img,w_433,h_516/https://akkaara.co.in/wp-content/uploads/2019/01/wind_chime_mid_product-433x516.jpg',
//       },

//   ];
  
//   export default ProductDetails;
  